create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date datetime(6), label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date datetime(6), label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date datetime(6), label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date datetime(6), label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, num_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKmesdd1k28dq0r18el7qmaayil foreign key (num_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, id_client bigint, primary key (numero)) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte add constraint FKfn9jafk7kn8gpmsxv9uhqna92 foreign key (id_client) references client (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(255), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table employe (numero bigint not null auto_increment, email varchar(255), nom varchar(255), prenom varchar(64), primary key (numero)) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table client (numero number(19,0) generated as identity, nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table compte (numero number(19,0) generated as identity, label varchar2(64 char), solde double precision, primary key (numero));
create table compte_client (num_compte number(19,0) not null, id_client number(19,0) not null);
create table employe (numero number(19,0) generated as identity, email varchar2(255 char), nom varchar2(255 char), prenom varchar2(64 char), primary key (numero));
create table operation (id_op number(19,0) generated as identity, date date, label varchar2(255 char), montant double precision, ref_compte number(19,0), primary key (id_op));
alter table compte_client add constraint FKrcpshpa8s6es8hnk7mjn3rlnc foreign key (id_client) references client;
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte;
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte;
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), email varchar(255), primary key (numero)) engine=InnoDB;
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), email varchar(255), primary key (numero)) engine=InnoDB;
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (numero bigint not null auto_increment, label varchar(64), solde double precision, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, nom varchar(255), prenom varchar(64), email varchar(255), primary key (numero)) engine=InnoDB;
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), primary key (numero)) engine=InnoDB;
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat integer, nom varchar(255), prenom varchar(64), email varchar(255), primary key (numero)) engine=InnoDB;
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), primary key (numero)) engine=InnoDB;
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), primary key (numero)) engine=InnoDB;
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
create table adresse (id bigint not null auto_increment, code_postal varchar(255), rue varchar(255), ville varchar(255), primary key (id)) engine=InnoDB;
create table compte (type_compte varchar(31) not null, numero bigint not null auto_increment, label varchar(64), solde double precision, taux_interet integer, primary key (numero)) engine=InnoDB;
create table compte_client (num_compte bigint not null, id_client bigint not null) engine=InnoDB;
create table operation (id_op bigint not null auto_increment, date date, label varchar(255), montant double precision, ref_compte bigint, primary key (id_op)) engine=InnoDB;
create table personne (type_personne varchar(31) not null, numero bigint not null auto_increment, etat varchar(255), nom varchar(255), prenom varchar(64), email varchar(255), id_adresse bigint, primary key (numero)) engine=InnoDB;
alter table personne add constraint UK_6nau3abvodhi54ln7rjx4liao unique (id_adresse);
alter table compte_client add constraint FKjtda3vg1tmnwdb5ydpnpahcnn foreign key (id_client) references personne (numero);
alter table compte_client add constraint FKtdijggku081be8w75ypgg3wai foreign key (num_compte) references compte (numero);
alter table operation add constraint FKn4dupl0ql813fl2mfvryxns49 foreign key (ref_compte) references compte (numero);
alter table personne add constraint FK16gp2enalx39031p3njj7l1xt foreign key (id_adresse) references adresse (id);
