drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
drop table if exists compte;
drop table if exists employe;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKmesdd1k28dq0r18el7qmaayil;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte drop foreign key FKfn9jafk7kn8gpmsxv9uhqna92;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
alter table compte_client drop foreign key FKrcpshpa8s6es8hnk7mjn3rlnc;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists client;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists employe;
drop table if exists operation;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
drop table client cascade constraints;
drop table compte cascade constraints;
drop table compte_client cascade constraints;
drop table employe cascade constraints;
drop table operation cascade constraints;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
alter table compte_client drop foreign key FKjtda3vg1tmnwdb5ydpnpahcnn;
alter table compte_client drop foreign key FKtdijggku081be8w75ypgg3wai;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
alter table personne drop foreign key FK16gp2enalx39031p3njj7l1xt;
drop table if exists adresse;
drop table if exists compte;
drop table if exists compte_client;
drop table if exists operation;
drop table if exists personne;
