drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
