drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
drop table if exists compte;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists operation;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
alter table compte drop foreign key FKjxrv80rjyauqbytcyamoyr3es;
alter table operation drop foreign key FKn4dupl0ql813fl2mfvryxns49;
drop table if exists compte;
drop table if exists customer;
drop table if exists operation;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
drop table compte cascade constraints;
drop table customer cascade constraints;
drop table operation cascade constraints;
